#define SM_IDD 8940

#define SM_POOL_LISTBOX_IDC 8941
#define SM_CURRENT_LISTBOX_IDC 8942

#define SM_TAKE_BUTTON_IDC 8943
#define SM_STORE_BUTTON_IDC 8944
#define SM_CLOSE_BUTTON_IDC 8945

#define TO_STRING(NAME_OF) #NAME_OF


#define SM_DISPLAY_VAR_STR "KISKA_SM_display"
#define GET_SM_DISPLAY localNamespace getVariable [SM_DISPLAY_VAR_STR,displayNull]

#define SM_POOL_LIST_CTRL_VAR_STR "KISKA_SM_poolListBox_ctrl"
#define GET_SM_POOL_LIST_CTRL (GET_SM_DISPLAY) getVariable [SM_POOL_LIST_CTRL_VAR_STR,controlNull]

#define SM_CURRENT_LIST_CTRL_VAR_STR "KISKA_SM_currentListBox_ctrl"
#define GET_SM_CURRENT_LIST_CTRL (GET_SM_DISPLAY) getVariable [SM_CURRENT_LIST_CTRL_VAR_STR,controlNull]


#define SM_POOL_GVAR KISKA_SM_pool
#define SM_POOL_VAR_STR TO_STRING(SM_POOL_GVAR)
#define GET_SM_POOL missionNamespace getVariable [SM_POOL_VAR_STR,[]]
#define SM_DISPLAYED_POOL_VAR_STR "KISKA_SM_displayedPool"
#define GET_SM_DISPLAYED_POOL (GET_SM_POOL_LIST_CTRL) getVariable [SM_DISPLAYED_POOL_VAR_STR,[]]
