#define TM_IDD 9940

#define TM_POOL_LISTBOX_IDC 9941
#define TM_CURRENT_LISTBOX_IDC 9942

#define TM_TAKE_BUTTON_IDC 9943
#define TM_STORE_BUTTON_IDC 9944
#define TM_CLOSE_BUTTON_IDC 9945

#define TO_STRING(NAME_OF) #NAME_OF
#define TM_POOL_GVAR KISKA_TM_pool
#define TM_POOL_VAR_STR TO_STRING(SM_POOL_GVAR)
#define GET_TM_POOL missionNamespace getVariable [TM_POOL_VAR_STR,[]]
#define TM_DISPLAYED_POOL_VAR_STR "KISKA_TM_displayedPool"
#define GET_TM_DISPLAYED_POOL (GET_TM_POOL_LIST_CTRL) getVariable [TM_DISPLAYED_POOL_VAR_STR,[]]

#define TM_DISPLAY_VAR_STR "KISKA_TM_display"
#define GET_TM_DISPLAY localNamespace getVariable [TM_DISPLAY_VAR_STR,displayNull]

#define TM_POOL_LIST_CTRL_VAR_STR "KISKA_TM_poolListBox_ctrl"
#define GET_TM_POOL_LIST_CTRL (GET_TM_DISPLAY) getVariable [TM_POOL_LIST_CTRL_VAR_STR,controlNull]

#define TM_CURRENT_LIST_CTRL_VAR_STR "KISKA_TM_currentListBox_ctrl"
#define GET_TM_CURRENT_LIST_CTRL (GET_TM_DISPLAY) getVariable [TM_CURRENT_LIST_CTRL_VAR_STR,controlNull]

#define RESERVED_TRAITS ["MEDIC","ENGINEER","EXPLOSIVESPECIALIST","UAVHACKER"]
#define NUMBER_TRAITS ["LOADCOEF","AUDIBLECOEF","CAMOUFLAGECOEF"]
