#define TM_IDD 9940

#define TM_POOL_LISTBOX_IDC 9941
#define TM_CURRENT_LISTBOX_IDC 9942

#define TM_TAKE_BUTTON_IDC 9943
#define TM_STORE_BUTTON_IDC 9944
#define TM_CLOSE_BUTTON_IDC 9945

#define TO_STRING(NAME_OF) #NAME_OF
#define POOL_GVAR KISKA_TM_pool